### ISSUE TITLE
The pipe has been ended

### ISSUE THREAD

**Issue by leshacsharp** [AlturosDestinations/Alturos.VideoInfo#15]
Hi, when i try to get video info by byte array i am getting 
System.IO.IOException: The pipe has been ended.
![2](https://user-images.githubusercontent.com/25509535/75675476-4a539f00-5c98-11ea-9328-f3dc8b8ce639.png)

**Comment by leshacsharp** [comment]
![3](https://user-images.githubusercontent.com/25509535/75677136-d4e9cd80-5c9b-11ea-91c4-85d1892e2fc6.png)

**Comment by tinohager** [comment]
What is the output of `cmd` execute following command  `ffprobe -v quiet -print_format json -show_format -show_streams yourvideo.mp4`

**Comment by leshacsharp** [comment]
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "1/60",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "has_b_frames": 1,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 31,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30/1",
            "avg_frame_rate": "30/1",
            "time_base": "1/90000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 19521000,
            "duration": "216.900000",
            "bit_rate": "766031",
            "bits_per_raw_sample": "8",
            "nb_frames": "6507",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2017-02-09T08:56:33.000000Z",
                "language": "und",
                "handler_name": "ISO Media file produced by Google Inc."
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/44100",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 9566208,
            "duration": "216.920816",
            "bit_rate": "125588",
            "nb_frames": "9342",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2017-02-09T08:56:33.000000Z",
                "language": "und",
                "handler_name": "ISO Media file produced by Google Inc."
            }
        }
    ],
    "format": {
        "filename": "video.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "216.920811",
        "size": "24280304",
        "bit_rate": "895453",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "isommp42",
            "creation_time": "2017-02-09T08:56:33.000000Z"
        }
    }
}

**Comment by tinohager** [comment]
Can you send me the video file?

**Comment by leshacsharp** [comment]
I have tried to get video info with different video files and always get this exception.
File: https://yadi.sk/i/alqYVC2uFA8sUw

**Comment by tinohager** [comment]
If you use the path instead of the video bytes?

**Comment by leshacsharp** [comment]
If i use the path all works, but i have REST API and i receive the stream. I can create temp file and use his path and then remove him, but i think it will be strange

**Comment by tinohager** [comment]
There is a mistake with your video on byte transfer that I can simulate here. I'll look into it. I hope you can use the temporary solution via the file at the moment.

**Comment by leshacsharp** [comment]
It works now!
But can you tell me why this is exception was happening?

**Comment by tinohager** [comment]
no i have not found out the reason yet

**Comment by leshacsharp** [comment]
I have notified that if i replace this is [code line](https://github.com/AlturosDestinations/Alturos.VideoInfo/blob/e1317e90e54f6e78553af0aa8942596862e9c37e/src/Alturos.VideoInfo/VideoAnalyzer.cs#L126)
on `  foreach (var b in mediaInput.FileContent)
                            {
                                ffprobeIn.WriteByte(b);
                            }`
Code will works without IOException, but i don't know why

**Comment by LKneringer** [comment]
Thanks for the input. Limiting the amount of bytes written at once seems to resolve the issue of encountering the IO exception.

Not every byte has to be written individually. In the latest commit we use a package size of 100000 bytes and it avoids the exception.

**Comment by leshacsharp** [comment]
Thank you all for resolving this problem
