### ISSUE TITLE
VideoFilePath with blank spaces.

### ISSUE THREAD

**Issue by JairoASuarez** [AlturosDestinations/Alturos.VideoInfo#8]
Hello, I have a bug when videoFilePath contains blank spaces. I call videoAnalyzer.GetVideoInfo(videoFilePaths) this method throws **System.NullReferenceException**.
https://github.com/AlturosDestinations/Alturos.VideoInfo/blob/db14333502cbaada1432ba61ac2878adad43453a/src/Alturos.VideoInfo/VideoAnalyzer.cs#L58

**Comment by LKneringer** [comment]
Could not replicate the exception, but could verify it doesn't work with blank spaces in the path.
Try surrounding the videoFilePath with quotation marks at the line you provided.
`Arguments = $"-v quiet -print_format json -show_format -show_streams \"{videoFilePath}\"",`

**Comment by tinohager** [comment]
We have update the logic can you test again [update](https://github.com/AlturosDestinations/Alturos.VideoInfo/pull/9)

**Comment by tinohager** [comment]
@JairoASuarez new version is also pushed to nuget
